twitch:
  client-id: "INVALID"
  client-secret: "INVALID"

channels:
  - IncantaGames

chat-handlers:
  ping:
    enabled: true
    command: "!ping"
    response: "Pong!"
    aliases:
  uptime:
    enabled: true
    command: "!uptime"
    response: null
    aliases:
  so:
    enabled: true
    command: "!so"
    response: null
    aliases:
      - "!shoutout"
  lurk:
    enabled: true
    command: "!lurk"
    response: null
    aliases:
  lurkers:
    enabled: true
    command: "!lurkers"
    response: null
    aliases:
  discord:
    enabled: true
    command: "!discord"
    response: "Join the Incanta Games Discord server at https://discord.gg/5hFrK2D"
    aliases:
  social:
    enabled: true
    command: "!social"
    response: >-
      https://discord.gg/5hFrK2D |
      https://twitter.com/RocklenMagic |
      https://reddit.com/r/rocklen |
      https://incanta.games/rocklen
    aliases:
  donate:
    enabled: true
    command: "!donate"
    response: >-
      If you feel generous enough to support Incanta Games
      bring magic to the world through games, you can donate
      at https://ko-fi.com/incanta.
    aliases:
      - "!donation"
      - "!support"

shout-outs:
  phanxgames:
    message: ""
  simpathey:
    message: ""

auto-chatters:
  channel: IncantaGames
  frequencyMs: 120000
  list:
    prime:
      enabled: true
      message: >-
        Did you know that you get a free Twitch subscription
        with your Amazon Prime subscription? Learn how to support
        your favorite streamer with it at https://bit.ly/2PPrE6x!
    discord:
      enabled: true
      message: >-
        Chat with us when we're off stream on our Discord!
        We usually respond pretty quickly and love to hear
        your ideas and feedback. Join at https://discord.gg/5hFrK2D

event-messages:
  subscription:
    enabled: true
    paid: "Thanks to @_USER_ for subscribing to the channel!"
    prime: "Thanks to @_USER_ for subscribing to the channel!"
  resubscription:
    enabled: true
    paid: "Thanks to @_USER_ for subscribing to the channel for a total of _SUBINFO_MONTHS_ months!"
    prime: "Thanks to @_USER_ for subscribing to the channel for a total of _SUBINFO_MONTHS_ months!"
  subscription-gift:
    enabled: true
    paid: "Thanks to _SUBINFO_GIFTER_ for gifting a subscription to _USER_!"
