twitch:
  client-id: "INVALID"
  client-secret: "INVALID"

channels:
  - IncantaGames

chat-handlers:
  ping:
    enabled: true
    mods-only: false
    command: "!ping"
    response: "Pong!"
    aliases:
  uptime:
    enabled: true
    mods-only: false
    command: "!uptime"
    response: null
    aliases:
  so:
    enabled: true
    mods-only: true
    command: "!so"
    response: null
    aliases:
      - "!shoutout"
  discord:
    enabled: true
    mods-only: false
    command: "!discord"
    response: "Join the Incanta Games Discord server at https://discord.gg/5hFrK2D"
    aliases:
  social:
    enabled: true
    mods-only: false
    command: "!social"
    response: >-
      https://discord.gg/5hFrK2D |
      https://twitter.com/RocklenMagic |
      https://reddit.com/r/rocklen |
      https://incanta.games/rocklen
    aliases:
  donate:
    enabled: true
    mods-only: false
    command: "!donate"
    response: >-
      If you feel generous enough to support Incanta Games
      bring magic to the world through games, you can donate
      at https://ko-fi.com/incanta.
    aliases:
      - "!donation"
      - "!support"
  set:
    enabled: true
    # this is set to false so the custom commands can be processed
    # the !set, !rm, and !clear commands will be mods only. the
    # temporary commands they create will not be mod only
    mods-only: false
    command: "!set" # `command` is ignored for this handler
    response: null
    aliases: # `aliases` is ignored for this handler

shout-outs:
  generic-message: >-
    Take a moment and check out @_USER_'s channel at https://twitch.tv/_USER_ and give them a follow!
  list:

auto-chatters:
  channel: IncantaGames
  frequencyMs: 120000
  list:
    prime:
      enabled: true
      message: >-
        Did you know that you get a free Twitch subscription
        with your Amazon Prime subscription? Learn how to support
        your favorite streamer with it at https://bit.ly/2PPrE6x!
    discord:
      enabled: true
      message: >-
        Chat with us when we're off stream on our Discord!
        We usually respond pretty quickly and love to hear
        your ideas and feedback. Join at https://discord.gg/5hFrK2D

event-messages:
  subscription:
    enabled: true
    paid: "Thanks to @_USER_ for subscribing to the channel!"
    prime: "Thanks to @_USER_ for subscribing to the channel!"
  resubscription:
    enabled: true
    paid: "Thanks to @_USER_ for subscribing to the channel for a total of _SUBINFO_MONTHS_ months!"
    prime: "Thanks to @_USER_ for subscribing to the channel for a total of _SUBINFO_MONTHS_ months!"
  subscription-gift:
    enabled: true
    paid: "Thanks to _SUBINFO_GIFTER_ for gifting a subscription to _USER_!"
